version: "3.1"
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api-financeiro-java
    image: financeiro-java:latest
    expose:
      - 8090
    ports:
      - 8092:8090
    depends_on:
      - rabbitmq
    environment:
      SPRING_RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USERNAME: admin
      RABBITMQ_PASSWORD: admin
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management
    ports:
      - 5672:5672
      - 15672:15672
#    volumes:
#      - /docker_conf/rabbitmq/data/:/var/lib/rabbitmq/
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin

  prometheus:
    container_name: prometheus
    image: prom/prometheus
    volumes:
    - "./src/main/resources/prometheus.yml:/etc/prometheus/prometheus.yml"
    command:
    - "--config.file=/etc/prometheus/prometheus.yml"
    ports:
    - "9090:9090"
    extra_hosts:
      - "host.docker.internal:172.18.0.1"
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
#    depends_on:
#      - prometheus
#      - mongo-mkt
#networks:
#  default:
#    external:
#      name: mongodb_network


